export const TECHNOLOGIES = [
  "React",
  "TypeScript",
  "UI/UX",
  "Accessibility",
  "Performance",
  "Design Systems",
  "Frontend Architecture",
  "Node.js",
  "Next.js",
  "Tailwind CSS",
  "Storybook",
  "Python",
  "AWS",
  "Sentry",
  "Datadog",
  "Git",
  "REST",
  "GraphQL",
  "Jest",
  "Testing Library",
];
